# Generated by Django 3.1.7 on 2021-03-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_category_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='first_part',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='second_part',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
